package com.oracle.dev.jdbc;

import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.IntStream;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import oracle.ucp.admin.UniversalConnectionPoolManagerBase;

public class HibernateVectorDataTypeOracleDatabase implements AutoCloseable {

  private static final long SAMPLE_VECTOR_ID = 1L;
  private static final String VECTOR_TABLE_NAME = "\"VECTOR_USER.vector_data\"";
  private static final Logger LOGGER = Logger.getLogger(HibernateVectorDataTypeOracleDatabase.class.getName());

  static {
    System.setProperty("oracle.ucp.enableShutdownHook", "false");
  }

  private final SessionFactory sessionFactory;

  public static void main(String[] args) {

    try (HibernateVectorDataTypeOracleDatabase example = new HibernateVectorDataTypeOracleDatabase()) {

      example.resetSampleData();

      // insert vectors
      IntStream.rangeClosed(1, 5).forEach(i -> example.insertVector());

      // read a vector
      HibernateVectorDataTypeEntity entity = example.readVector(SAMPLE_VECTOR_ID);

      if (entity != null) {
        System.out.println("Embedding retrieved: " + entity.getEmbedding()[0] + ", " + entity.getEmbedding()[1] + ", "
            + entity.getEmbedding()[2]);

        // update a vector
        entity.setEmbedding(new float[] { 4.0f, 5.0f, 6.0f });
        example.updateVector(entity);
        example.verifyEmbedding(SAMPLE_VECTOR_ID, new float[] { 4.0f, 5.0f, 6.0f });

        // delete a vector
        example.deleteVector(SAMPLE_VECTOR_ID);
        example.verifyDeleted(SAMPLE_VECTOR_ID);
        example.verifyVectorCount(4L);
      } else {
        throw new IllegalStateException("No entity found with ID " + SAMPLE_VECTOR_ID);
      }
    }
  }

  public HibernateVectorDataTypeOracleDatabase() {
    Properties properties = loadProperties();

    Configuration configuration = new Configuration().addProperties(properties)
        .addAnnotatedClass(HibernateVectorDataTypeEntity.class);

    sessionFactory = configuration.buildSessionFactory();
  }

  private void resetSampleData() {
    Transaction transaction = null;

    try (Session session = sessionFactory.openSession()) {
      transaction = session.beginTransaction();

      session.createNativeMutationQuery("truncate table " + VECTOR_TABLE_NAME).executeUpdate();
      session
          .createNativeMutationQuery(
              "alter table " + VECTOR_TABLE_NAME + " modify id generated by default as identity (restart start with 1)")
          .executeUpdate();

      transaction.commit();
    } catch (RuntimeException e) {
      if (transaction != null && transaction.isActive()) {
        transaction.rollback();
      }
      throw e;
    }
  }

  private void insertVector() {
    Transaction transaction = null;

    try (Session session = sessionFactory.openSession()) {
      transaction = session.beginTransaction();

      HibernateVectorDataTypeEntity entity = new HibernateVectorDataTypeEntity();
      entity.setEmbedding(new float[] { 1.0f, 2.0f, 3.0f });

      session.persist(entity);

      transaction.commit();
      logOperation("insertVector", "insertVector() - inserted vector " + formatVector(entity));
    } catch (RuntimeException e) {
      if (transaction != null && transaction.isActive()) {
        transaction.rollback();
      }
      throw e;
    }
  }

  public HibernateVectorDataTypeEntity readVector(long id) {
    try (Session session = sessionFactory.openSession()) {
      logOperation("readVector", "readVector() - reading vector id=" + id);
      HibernateVectorDataTypeEntity entity = session.get(HibernateVectorDataTypeEntity.class, id);

      if (entity != null) {
        LOGGER.info(() -> "readVector() - found vector " + formatVector(entity));
      } else {
        LOGGER.info(() -> "readVector() - no vector found for id=" + id);
      }

      return entity;
    }
  }

  public void updateVector(HibernateVectorDataTypeEntity entity) {
    Transaction transaction = null;

    try (Session session = sessionFactory.openSession()) {
      transaction = session.beginTransaction();

      logOperation("updateVector", "updateVector() - updating vector " + formatVector(entity));
      HibernateVectorDataTypeEntity mergedEntity = session.merge(entity);

      transaction.commit();
      LOGGER.info(() -> "updateVector() - updated vector " + formatVector(mergedEntity));
    } catch (RuntimeException e) {
      if (transaction != null && transaction.isActive()) {
        transaction.rollback();
      }
      throw e;
    }
  }

  public void deleteVector(long id) {
    Transaction transaction = null;

    try (Session session = sessionFactory.openSession()) {
      transaction = session.beginTransaction();

      HibernateVectorDataTypeEntity entity = session.get(HibernateVectorDataTypeEntity.class, id);

      if (entity != null) {
        String vector = formatVector(entity);
        logOperation("deleteVector", "deleteVector() - deleting vector " + vector);
        session.remove(entity);
        transaction.commit();
        LOGGER.info(() -> "deleteVector() - deleted vector " + vector);
      } else {
        LOGGER.info(() -> "deleteVector() - no vector found for id=" + id);
        transaction.commit();
      }
    } catch (RuntimeException e) {
      if (transaction != null && transaction.isActive()) {
        transaction.rollback();
      }
      throw e;
    }
  }

  private String formatVector(HibernateVectorDataTypeEntity entity) {
    return "id=" + entity.getId() + ", embedding=" + Arrays.toString(entity.getEmbedding());
  }

  private void logOperation(String methodName, String message) {
    LOGGER.logp(Level.INFO, HibernateVectorDataTypeOracleDatabase.class.getName(), methodName,
        System.lineSeparator() + message);
  }

  private void verifyEmbedding(long id, float[] expectedEmbedding) {
    HibernateVectorDataTypeEntity entity = readVector(id);

    if (entity == null || entity.getEmbedding().length != expectedEmbedding.length) {
      throw new IllegalStateException("Vector " + id + " was not updated as expected.");
    }

    for (int i = 0; i < expectedEmbedding.length; i++) {
      if (Float.compare(entity.getEmbedding()[i], expectedEmbedding[i]) != 0) {
        throw new IllegalStateException("Vector " + id + " was not updated as expected.");
      }
    }
  }

  private void verifyDeleted(long id) {
    if (readVector(id) != null) {
      throw new IllegalStateException("Vector " + id + " was not deleted as expected.");
    }
  }

  private void verifyVectorCount(long expectedCount) {
    try (Session session = sessionFactory.openSession()) {
      Long actualCount = session
          .createSelectionQuery("select count(e) from HibernateVectorDataTypeEntity e", Long.class).getSingleResult();

      if (actualCount != expectedCount) {
        throw new IllegalStateException(
            "Expected " + expectedCount + " remaining vectors, but found " + actualCount + ".");
      }
    }
  }

  @Override
  public void close() {
    if (sessionFactory != null && !sessionFactory.isClosed()) {
      sessionFactory.close();
    }

    UniversalConnectionPoolManagerBase.stopExecutionEnvironment();
  }

  private Properties loadProperties() {
    Properties properties = new Properties();

    try (InputStream inputStream = Thread.currentThread().getContextClassLoader()
        .getResourceAsStream("hibernate.properties")) {

      if (inputStream == null) {
        throw new IllegalStateException("hibernate.properties not found in src/main/resources");
      }

      properties.load(inputStream);
    } catch (IOException e) {
      throw new IllegalStateException("Could not load hibernate.properties", e);
    }

    applyEnvironmentOverride(properties, "DB_USERNAME", "hibernate.connection.username");
    applyEnvironmentOverride(properties, "DB_PASSWORD", "hibernate.connection.password");

    return properties;
  }

  private void applyEnvironmentOverride(Properties properties, String environmentVariable, String propertyName) {
    String value = System.getenv(environmentVariable);

    if (value != null && !value.isBlank()) {
      properties.setProperty(propertyName, value);
    }
  }
}
